server:
  port: 8080
spring:
  application:
    name: "tokenapp"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5544/accounts
    username: admin
    password: admin123
aws:
  region: "us-east-1"
  dynamodb:
    endpoint: "http://localhost:4566"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  aws:
    dynamodb:
      region: "us-east-1"
      endpoint: "http://localhost:4566"
      tableName: "SessionTokens"
generate-token:
  secret-key: 6l1NlUBZJOhxmpEnO51-bKHDEHlBl58-ak_etv-q8NHo04_Tq-cCf9mNDS7tal3RGDYASBboxjGEhu2mIn9gvg
  expiration-ms: 900000 //15 minutos en ms
api:
  base-path: /api/v1
  auth-path: /auth/login