server:
  port: 8080
spring:
  application:
    name: "tokenapp"
  devtools:
    add-properties: false
aws:
  region: "US_EAST_1"
  dynamodb:
    endpoint: "http://localhost:8000"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
